### ISSUE TITLE
Can't deploy

### ISSUE THREAD

**Issue by fpardon-upeo** [hsaraujo/apex-yaml-serializer#1]
Hi,

First of all: thanks for making this available. I tried installing it to a dev org but got some errors on deploy. It seems like it's missing the StringBuilder class

Error:(8, 13) Dependent class is invalid and needs recompilation:
 Class YAML : Dependent class is invalid and needs recompilation:
 Class YamlSerializer : Invalid type: StringBuilder

**Comment by hsaraujo** [comment]
Hi there.. could you try now?

**Comment by fpardon-upeo** [comment]
Works!

Thanks again for sharing this!
